package main

import (
	"log"

	configs "book-management/configs"
	_ "book-management/docs" // docs is generated by Swag CLI
	"book-management/internal/handlers"
	"book-management/internal/repositories"
	router "book-management/internal/routers"
	"book-management/internal/services"
	database "book-management/pkg/databases"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger" // swagger middleware
)

// @title Book Management API
// @version 1.0
// @description This is a simple Book Management API built with Golang and Gin
// @host localhost:8080
// @BasePath /api
func main() {
	// 1. Load config
	cfg := configs.LoadConfig()

	// 2. Connect DB
	db, err := database.ConnectPostgres(cfg)
	if err != nil {
		log.Fatal("❌ Failed to connect to database: ", err)
	}

	// 3. Init repository, service, handler
	authorRepo := repositories.NewAuthorRepository()
	authorService := services.NewAuthorService(authorRepo, db)
	authorHandler := handlers.NewAuthorHandler(authorService)

	// 4. Setup Gin router
	server := router.NewRouter(authorHandler)

	// 5. Swagger route
	server.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// 6. Start server
	port := cfg.HTTPPort
	log.Printf("🚀 Server running on http://localhost:%s\n", port)
	if err := server.Run(":" + port); err != nil {
		log.Fatal(err)
	}
}
