FROM golang:1.25-alpine3.22

# Install Air
RUN apk add --no-cache git curl bash \
    && go install github.com/air-verse/air@latest

WORKDIR /app

# Copy go.mod & go.sum to cache dependency
COPY go.mod go.sum ./
RUN go mod download

# Copy all source
COPY . .

CMD ["air", "-c", ".air.toml"]
